In [4]:
import numpy as np

In [5]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
np.array([3.14, 2.5, 7.43, 9.8], dtype='uint8')

array([3, 2, 7, 9], dtype=uint8)

In [10]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.random.random((3, 3))

array([[0.56064422, 0.85833897, 0.28899   ],
       [0.75402761, 0.12429927, 0.22200349],
       [0.24715209, 0.18379415, 0.16779934]])

In [28]:
np.random.normal(0, 1, (3, 3))

array([[-0.33158067,  0.77174263, -0.18169677],
       [ 0.37915211, -1.49704536,  1.48634203],
       [-0.72278539, -0.90622442,  1.32920503]])

In [32]:
np.random.randint(0, 10, (3, 3))

array([[1, 2, 4],
       [9, 3, 3],
       [9, 0, 9]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.empty(3)

array([1., 1., 1.])