In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [4]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [5]:
print("x3 dtype:", x3.dtype)

x3 dtype: int64


In [6]:
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[0]

5

In [9]:
x1[4]

7

In [10]:
x1[-1]

9

In [11]:
x1[-2]

7

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[0,0]

3

In [14]:
x2[2,2]

7

In [15]:
x2[-1,-2]

7

In [16]:
x2[0,0] = 10
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [17]:
x = np.arange(10)

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[:5]

array([0, 1, 2, 3, 4])

In [20]:
x[5:]

array([5, 6, 7, 8, 9])

In [21]:
x[4:7]

array([4, 5, 6])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
x[1::3]
#general slicing: x[start:stop:step]

array([1, 4, 7])

In [24]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
x[5::-2]

array([5, 3, 1])

In [26]:
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [27]:
x2[:2, :3]

array([[10,  5,  2],
       [ 7,  6,  8]])

In [28]:
x2[:3, ::2]

array([[10,  2],
       [ 7,  8],
       [ 1,  7]])

In [29]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 10]])

In [30]:
x2[:, 0]

array([10,  7,  1])

In [31]:
x2[0, :]

array([10,  5,  2,  4])

In [32]:
x2[0]

array([10,  5,  2,  4])

In [33]:
x2_sub = x2[:2, :2]

In [34]:
x2_sub

array([[10,  5],
       [ 7,  6]])

In [35]:
x2_sub[0, 0] = 999

In [36]:
x2_sub

array([[999,   5],
       [  7,   6]])

In [37]:
x2

array([[999,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [38]:
x2_sub_copy = x2[:2, :2].copy()

In [39]:
x2_sub_copy

array([[999,   5],
       [  7,   6]])

In [40]:
x2_sub_copy[0, 0] = 42

In [46]:
x2

array([[999,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [42]:
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [47]:
grid = np.arange(1, 10).reshape((3, 3))

In [48]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [50]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [51]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [52]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [55]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [61]:
z = [99, 99, 99]
np.concatenate((x, y, z))

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [62]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [63]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [64]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [65]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [66]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [67]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])