In [4]:
import numpy as np

In [5]:
x = np.arange(4)

In [7]:
x+5

array([5, 6, 7, 8])

In [8]:
x-5

array([-5, -4, -3, -2])

In [9]:
x*2

array([0, 2, 4, 6])

In [10]:
x/2

array([0. , 0.5, 1. , 1.5])

In [11]:
x//2

array([0, 0, 1, 1])

In [12]:
-x

array([ 0, -1, -2, -3])

In [13]:
x**2

array([0, 1, 4, 9])

In [14]:
2**x

array([1, 2, 4, 8])

In [15]:
x%2

array([0, 1, 0, 1])

In [16]:
x = np.arange(-2, 3)

In [17]:
abs(x)

array([2, 1, 0, 1, 2])

In [18]:
x = np.array([3-4j, 4+3j, 2+0j, 0+1j])

In [19]:
abs(x)

array([5., 5., 2., 1.])

In [22]:
theta = np.linspace(0, np.pi, 3)

In [23]:
theta

array([0.        , 1.57079633, 3.14159265])

In [25]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [26]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [27]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [28]:
x = [-1, 0, 1]

In [29]:
x

[-1, 0, 1]

In [31]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [32]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [33]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [34]:
x = [1, 2, 3]

In [35]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [36]:
np.exp2(x)

array([2., 4., 8.])

In [38]:
np.power(3, x)

array([ 3,  9, 27])

In [39]:
x = [1, 2, 4, 10]

In [40]:
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [41]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [42]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

In [43]:
x = [0, 0.001, 0.01, 0.1]

In [44]:
np.expm1(x)

array([0.        , 0.0010005 , 0.01005017, 0.10517092])

In [45]:
np.log1p(x)

array([0.        , 0.0009995 , 0.00995033, 0.09531018])

In [49]:
from scipy import special

In [51]:
x = [1, 5, 10]

In [52]:
special.gamma(x)

array([1.0000e+00, 2.4000e+01, 3.6288e+05])

In [53]:
special.gammaln(x)

array([ 0.        ,  3.17805383, 12.80182748])

In [54]:
special.beta(x, 2)

array([0.5       , 0.03333333, 0.00909091])

In [55]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
y

array([ 0., 10., 20., 30., 40.])

In [61]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
y
#If we had instead written y[::2] = 2 ** x, this would have resulted
#in the creation of a temporary array to hold the results of 2 ** x, 
#followed by a second operation copying those values into the y array.

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [62]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [63]:
np.multiply.reduce(x)

120

In [64]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [65]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [66]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])